name: test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Test:
    name: Run test codes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install bun
        run: npm i -g bun
      - name: Install packages
        run: bun install
      - name: Show coverage
        env:
          TZ: 'Asia/Tokyo'
        run: bun test
